/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.infotech.views;

import com.mycompany.infotech.models.Produto;
import com.mycompany.infotech.controller.ProdutoController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Icaro
 */
public class ConsultaProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form Vlew_ConsultaProduto
     */
    public ConsultaProdutoView() {
        initComponents();
        setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_pesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmb_coluna = new javax.swing.JComboBox<>();
        btn_busca = new javax.swing.JButton();
        tbl = new javax.swing.JScrollPane();
        tbl_produto = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_Atualizar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_Adicionar = new javax.swing.JButton();
        btn_atualizartabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de produto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Consotra por");

        jLabel2.setText("Na Coluna");

        cmb_coluna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nome do Produto", "Marca", "Modelo", "Especificaçoes", "Nome do Fornecedor", "CNPJ", "Contato", "E-mail", "Quantidade", "Valor de Compra", "Valor de Venda" }));

        btn_busca.setText("Buscar");
        btn_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cmb_coluna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_coluna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_busca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Marca", "Modelo", "Descrição", "Valor de Compro", "Valor de Venda", "Nome do Fornecedor", "CNPJ", "Contato", "Email", "DATA de Aquisição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.setViewportView(tbl_produto);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        btn_Excluir.setForeground(new java.awt.Color(204, 0, 0));
        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btn_Adicionar.setText("Adicionar");
        btn_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdicionarActionPerformed(evt);
            }
        });

        btn_atualizartabela.setText("Atualizar tabela");
        btn_atualizartabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizartabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_Adicionar)
                .addGap(18, 18, 18)
                .addComponent(btn_Atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_atualizartabela)
                .addGap(18, 18, 18)
                .addComponent(btn_Excluir)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Atualizar)
                    .addComponent(btn_Excluir)
                    .addComponent(btn_Adicionar)
                    .addComponent(btn_atualizartabela))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tbl))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbl, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaActionPerformed
        Busca();
    }//GEN-LAST:event_btn_buscaActionPerformed

    private void btn_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdicionarActionPerformed
        add();
    }//GEN-LAST:event_btn_AdicionarActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        Atualizar();
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        Excluir();
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_atualizartabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizartabelaActionPerformed
        setTable();
    }//GEN-LAST:event_btn_atualizartabelaActionPerformed
    
    /**
     * função para buscar um elemento em determinada colunada da tabela produto
     */
    public void Busca(){
        //JOptionPane.showMessageDialog(null, "cmb "+cmb_coluna.getSelectedItem()+" txt "+txt_pesquisa.getText());
        if (campos(cmb_coluna.getSelectedIndex(), txt_pesquisa.getText())){
            
            ArrayList<String[]> listaProduto = ProdutoController.Busca((String) cmb_coluna.getSelectedItem(), txt_pesquisa.getText());
        
            DefaultTableModel tmProdutos = new DefaultTableModel();

            tmProdutos.addColumn("ID");
            tmProdutos.addColumn("Nome");
            tmProdutos.addColumn("Marca");
            tmProdutos.addColumn("Modelo");
            tmProdutos.addColumn("Descrição");
            tmProdutos.addColumn("Quantidade");
            tmProdutos.addColumn("Valor de venda");
            tmProdutos.addColumn("Valor de compra");
            tmProdutos.addColumn("Fornecedor");
            tmProdutos.addColumn("CNPJ");
            tmProdutos.addColumn("Contato");
            tmProdutos.addColumn("Email");
            tmProdutos.addColumn("Data de Aquisição");

            tbl_produto.setModel(tmProdutos);

            tmProdutos.setRowCount(0);
            
            if (listaProduto.size()>0) {
                System.out.println("itens retornados "+listaProduto.size());
                for (String[] p : listaProduto){
                    tmProdutos.addRow(p);
                }
            }else{
                System.out.println("não foi encontrado nenhum registro");
                JOptionPane.showMessageDialog(this, "não foi encontrado nenhum registro");
            }

            tbl_produto.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbl_produto.getColumnModel().getColumn(1).setPreferredWidth(150);
            tbl_produto.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbl_produto.getColumnModel().getColumn(3).setPreferredWidth(125);
            tbl_produto.getColumnModel().getColumn(4).setPreferredWidth(50);
            tbl_produto.getColumnModel().getColumn(5).setPreferredWidth(25);
            tbl_produto.getColumnModel().getColumn(6).setPreferredWidth(50);
            tbl_produto.getColumnModel().getColumn(7).setPreferredWidth(50);
            tbl_produto.getColumnModel().getColumn(9).setPreferredWidth(110);
            
        }
    }
    
    /**
     * função para excluir um produto
     */
    public void Excluir(){
        if (tbl_produto.getSelectedRow()>=0) {
            int nulinha = tbl_produto.getSelectedRow();
            
            int proceed = JOptionPane.showConfirmDialog(this,"Tem certeza que deseja excluir este produto?\nNome do Produto "+tbl_produto.getModel().getValueAt(nulinha, 1).toString(),"Excluir",JOptionPane.YES_NO_OPTION);
            
            if (proceed == JOptionPane.YES_OPTION) {
                
                if (ProdutoController.exclusao(Integer.parseInt(tbl_produto.getModel().getValueAt(nulinha, 0).toString()))) {
                    JOptionPane.showMessageDialog(this, "Produto excluído");
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao excluir produto");
                }
                
                setTable();
                
            }else{
                JOptionPane.showMessageDialog(this, "Exclusão Cancelada\nA Exclusão do Produto "+tbl_produto.getModel().getValueAt(nulinha, 1).toString()+" Não foi concluída");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecione um produto");
        }
    }
    
    /**
     * função para chamar a tela de cadastro de produto
     */
    public void add(){
        CadastroProdutoView tela = new CadastroProdutoView();
        tela.setVisible(true);
        
        ConsultaProdutoView.this.dispose();
    }
    
    /**
     * função para chamar a tela de alteração dos dados do produdo
     */
    public void Atualizar(){
        if (tbl_produto.getSelectedRow()>=0) {
            
            Produto p = new Produto();
            int nulinha = tbl_produto.getSelectedRow();
            int er =0;
            
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            
            try {

                p.setID(Integer.parseInt(tbl_produto.getModel().getValueAt(nulinha, 0).toString()));
                er++;
                p.setNome_Produto(tbl_produto.getModel().getValueAt(nulinha, 1).toString());
                er++;
                p.setMarca(tbl_produto.getModel().getValueAt(nulinha, 2).toString());
                er++;
                p.setModelo(tbl_produto.getModel().getValueAt(nulinha, 3).toString());
                er++;
                p.setDescricao(tbl_produto.getModel().getValueAt(nulinha, 4).toString());
                er++;
                p.setQuantidade(Integer.parseInt(tbl_produto.getModel().getValueAt(nulinha, 5).toString()));
                er++;
                p.setValor_venda(Double.parseDouble(tbl_produto.getModel().getValueAt(nulinha, 6).toString()));
                er++;
                p.setValor_compra(Double.parseDouble(tbl_produto.getModel().getValueAt(nulinha, 7).toString()));
                er++;
                p.setFornecedor(tbl_produto.getModel().getValueAt(nulinha, 8).toString());
                er++;
                p.setCNPJ(tbl_produto.getModel().getValueAt(nulinha, 9).toString());
                er++;
                p.setContato(tbl_produto.getModel().getValueAt(nulinha, 10).toString());
                er++;
                p.setEmail(tbl_produto.getModel().getValueAt(nulinha, 11).toString());
                er++;
                p.setData_aquisicao(formato.parse(tbl_produto.getModel().getValueAt(nulinha, 12).toString()));

                CadastroProdutoView tela = new CadastroProdutoView(p);
                tela.setVisible(true);
                
                ConsultaProdutoView.this.dispose();

            } /*catch (ParseException ex) {
                System.out.println("Erro "+er+" de conversão");
                System.out.println(ex); /*catch (ParseException ex) {
                System.out.println("Erro "+er+" de conversão");
                System.out.println(ex);
            }*/catch (NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Erro "+er+"\n"+ex);
                System.out.println("Erro "+er+" de conversão");
            } catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Erro "+er+"\n"+ex);
                System.out.println("Erro "+er+" de conversão");
            } 

        }else{
            JOptionPane.showMessageDialog(this, "selecione um produto");
        }
    }
    
    /**
     * função para validar os campos
     * @param text String a ser validada
     * @param item int identifique o tipo de validar
     * @return boolean retornar <b>true</b> se o campo de acordo. se não retorna <b>false</b>
     */
    public boolean campos(int item, String text){
        String[] linha ={"ID","Nome do Produto","Marca","Modelo","Especificaçoes","Nome do Fornecedor","CNPJ","Contato","E-mail","Quantidade","Valor de Compra","Valor de Venda","Data de Aquisição"};
        try {       
            int n;
            double m;
            if (text.trim().replace(" ", "").replace("-", "").replace("+", "").replace("/", "").replace(".", "").equals("")) {
                JOptionPane.showMessageDialog(null, "preencha o campo");
                return false;
            }else{
                switch(item){
                    case 1:
                    case 2:
                    case 3:
                    case 5:    
                        if (45 >= text.length()) {
                            return true;
                        }else{
                            JOptionPane.showMessageDialog(null, linha[item]+" excedeu o tamanho do campo");
                            return false;
                        }
                    case 4:
                        if (300 >= text.length()) {
                            return true;
                        }else{
                            JOptionPane.showMessageDialog(null, linha[item]+" excedeu o tamanho do campo");
                            return false;
                        }
                    case 6:
                        if (14 >= text.replace(".", "").replace("-", "").replace("/", "").length()) {
                            return true;
                        }else{
                            JOptionPane.showMessageDialog(null, linha[item]+" excedeu o tamanho do campo");
                            return false;
                        }
                    case 7:
                        if (13 >= text.replace(" ", "").replace("+", "").replace("-", "").length()) {
                            return true;
                        }else{
                            JOptionPane.showMessageDialog(null, linha[item]+" excedeu o tamanho do campo");
                            return false;
                        }
                    case 8:
                        if (50 >= text.length()) {
                            return true;
                        }else{
                            JOptionPane.showMessageDialog(null, linha[item]+" excedeu o tamanho do campo");
                            return false;
                        }
                    case 9:
                    case 0:   
                        n = Integer.parseInt(text);
                        return true;
                    case 10:
                    case 11:
                        m = Double.parseDouble(text.replace(",", "."));
                        return true;
//                    case 12:
//                        DataFormat(text);
//                        return true;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, linha[item]+" não pode ser convertido");
            return false;
        }
        return true;
    }
    
    /**
     * função para Popular a tabela produto
     */
    public void setTable(){
        
        ArrayList<String[]> listaProduto = ProdutoController.selecionar();
        
        DefaultTableModel tmProdutos = new DefaultTableModel();
        
        tmProdutos.addColumn("ID");
        tmProdutos.addColumn("Nome");
        tmProdutos.addColumn("Marca");
        tmProdutos.addColumn("Modelo");
        tmProdutos.addColumn("Descrição");
        tmProdutos.addColumn("Quantidade");
        tmProdutos.addColumn("Valor de venda");
        tmProdutos.addColumn("Valor de compra");
        tmProdutos.addColumn("Fornecedor");
        tmProdutos.addColumn("CNPJ");
        tmProdutos.addColumn("Contato");
        tmProdutos.addColumn("Email");
        tmProdutos.addColumn("Data de Aquisição");
        
        tbl_produto.setModel(tmProdutos);
        
        tmProdutos.setRowCount(0);
        
        for (String[] p : listaProduto){
            tmProdutos.addRow(p);
        }
        
        tbl_produto.getColumnModel().getColumn(0).setPreferredWidth(20);
        tbl_produto.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_produto.getColumnModel().getColumn(2).setPreferredWidth(50);
        tbl_produto.getColumnModel().getColumn(3).setPreferredWidth(125);
        tbl_produto.getColumnModel().getColumn(4).setPreferredWidth(50);
        tbl_produto.getColumnModel().getColumn(5).setPreferredWidth(25);
        tbl_produto.getColumnModel().getColumn(6).setPreferredWidth(50);
        tbl_produto.getColumnModel().getColumn(7).setPreferredWidth(50);
        tbl_produto.getColumnModel().getColumn(9).setPreferredWidth(110);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Adicionar;
    private javax.swing.JButton btn_Atualizar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_atualizartabela;
    private javax.swing.JButton btn_busca;
    private javax.swing.JComboBox<String> cmb_coluna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane tbl;
    private javax.swing.JTable tbl_produto;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
