package com.mycompany.infotech.views;

import com.mycompany.infotech.controller.RelatorioController;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author welli
 */
public class RelatorioProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public RelatorioProdutoView() {
        initComponents();
        rbtn_Sintetico.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gbnt_TipoRelato = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_clinetes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Items = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jdata_inicio = new com.toedter.calendar.JDateChooser();
        jdata_fim = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbtn_Analitico = new javax.swing.JRadioButton();
        rbtn_Sintetico = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de vendas");

        tbl_clinetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Data", "CPF", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_clinetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clinetesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_clinetes);

        tbl_Items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Produto", "Produto", "Quantidade", "Valor Unitario", "Qtd em Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_Items);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Periodo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("De");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Até");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jdata_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jdata_fim, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdata_inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jdata_fim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        Gbnt_TipoRelato.add(rbtn_Analitico);
        rbtn_Analitico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbtn_Analitico.setText("Analítico");
        rbtn_Analitico.setActionCommand("Analitico");
        rbtn_Analitico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtn_AnaliticoMouseClicked(evt);
            }
        });

        Gbnt_TipoRelato.add(rbtn_Sintetico);
        rbtn_Sintetico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbtn_Sintetico.setText("Sintético");
        rbtn_Sintetico.setActionCommand("Sintetico");
        rbtn_Sintetico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtn_SinteticoMouseClicked(evt);
            }
        });
        rbtn_Sintetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_SinteticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Sintetico)
                .addGap(18, 18, 18)
                .addComponent(rbtn_Analitico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Analitico)
                    .addComponent(rbtn_Sintetico))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (Gbnt_TipoRelato.getSelection().getActionCommand().equalsIgnoreCase("Sintetico")) {
            RSC();
        }else{
            RAC();
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void rbtn_SinteticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_SinteticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_SinteticoActionPerformed

    private void tbl_clinetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clinetesMouseClicked
        if (Gbnt_TipoRelato.getSelection().getActionCommand().equalsIgnoreCase("Sintetico")) {
            RSP();
        }else{
            RAP();
        }
    }//GEN-LAST:event_tbl_clinetesMouseClicked

    private void rbtn_SinteticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtn_SinteticoMouseClicked
        setTipoR();
    }//GEN-LAST:event_rbtn_SinteticoMouseClicked

    private void rbtn_AnaliticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtn_AnaliticoMouseClicked
        setTipoR();
    }//GEN-LAST:event_rbtn_AnaliticoMouseClicked

    /**
     * função para atualizar o tipo de relatório na tabela cliente
     */
    public void setTipoR(){
        if (tbl_clinetes.getRowCount()>0) {
            if (Gbnt_TipoRelato.getSelection().getActionCommand().equalsIgnoreCase("Sintetico")) {
                RSC();
            }else{
                RAC();
            }
        }
    }
    
    /**
     * função para gerar um relatório analítico dos itens de um pedido do cliente
     */
    public void RAP(){
        int linha = tbl_clinetes.getSelectedRow();
        if (linha>=0) {
            
            ArrayList<String[]> listaItem = RelatorioController.RAP(Integer.parseInt(tbl_clinetes.getModel().getValueAt(linha, 3).toString()));

            DefaultTableModel tmItem = new DefaultTableModel();

            tmItem.addColumn("Produto");
            tmItem.addColumn("Marca");
            tmItem.addColumn("Modelo");
            tmItem.addColumn("Quantidade");
            tmItem.addColumn("Valor de Venda");
            tmItem.addColumn("Valor de Compra");
            
            tbl_Items.setModel(tmItem);

            tmItem.setRowCount(0);

            for (String[] p : listaItem){
                tmItem.addRow(p);
            }

            tbl_Items.getColumnModel().getColumn(0).setPreferredWidth(150);
            tbl_Items.getColumnModel().getColumn(1).setPreferredWidth(75);
            tbl_Items.getColumnModel().getColumn(2).setPreferredWidth(75);
            tbl_Items.getColumnModel().getColumn(3).setPreferredWidth(20);
            tbl_Items.getColumnModel().getColumn(4).setPreferredWidth(100);
            tbl_Items.getColumnModel().getColumn(5).setPreferredWidth(100);
            
        }
    }
    
    /**
     * função para gerar um relatório sintético dos itens de todos pedidos de um cliente em determinado período
     */
    public void RSP(){
        int linha = tbl_clinetes.getSelectedRow();
        if (linha>=0) {
            
            ArrayList<String[]> listaItem = RelatorioController.RSP(Integer.parseInt(tbl_clinetes.getModel().getValueAt(linha, 0).toString()),jdata_inicio.getDate(),jdata_fim.getDate());

            DefaultTableModel tmItem = new DefaultTableModel();

            tmItem.addColumn("Produto");
            tmItem.addColumn("Quantidade");
            tmItem.addColumn("Valor total");
            
            tbl_Items.setModel(tmItem);

            tmItem.setRowCount(0);

            for (String[] p : listaItem){
                tmItem.addRow(p);
            }

            tbl_Items.getColumnModel().getColumn(0).setPreferredWidth(150);
            tbl_Items.getColumnModel().getColumn(1).setPreferredWidth(20);
            tbl_Items.getColumnModel().getColumn(2).setPreferredWidth(100);
        }
    }
    
    /**
     * função para gerar um relatório analítico dos pedidos de todos os clientes em determinado período
     */
    public void RAC(){
        Date inicio = jdata_inicio.getDate();
        Date fim = jdata_fim.getDate();
        
        if (inicio!=null && fim!=null && inicio.before(fim)) {
        
            ArrayList<String[]> listaCliente = RelatorioController.RAC(inicio, fim);

            DefaultTableModel tmCliente = new DefaultTableModel();

            tmCliente.addColumn("ID do Cliente");
            tmCliente.addColumn("Nome do Cliente");
            tmCliente.addColumn("CPF");
            tmCliente.addColumn("ID do Pedido");
            tmCliente.addColumn("Quantidade de itens");
            tmCliente.addColumn("Valor de todos pedidos");
            tmCliente.addColumn("Data da compra");

            tbl_clinetes.setModel(tmCliente);

            tmCliente.setRowCount(0);

            for (String[] p : listaCliente){
                tmCliente.addRow(p);
            }

            tbl_clinetes.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbl_clinetes.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbl_clinetes.getColumnModel().getColumn(2).setPreferredWidth(75);
            tbl_clinetes.getColumnModel().getColumn(3).setPreferredWidth(20);
            tbl_clinetes.getColumnModel().getColumn(4).setPreferredWidth(20);
            tbl_clinetes.getColumnModel().getColumn(5).setPreferredWidth(125);
            tbl_clinetes.getColumnModel().getColumn(6).setPreferredWidth(100);
        }else{
            JOptionPane.showMessageDialog(this, "Data inválida\nverifique os campos das datas");
        }
    }
    
    /**
     * função para gerar um relatório sintético dos pedidos de todos os clientes agrupados por cliente em determinado período
     */
    public void RSC(){
        Date inicio = jdata_inicio.getDate();
        Date fim = jdata_fim.getDate();
        
        if (inicio!=null && fim!=null && (inicio.before(fim) || inicio.equals(fim))) {
        
            ArrayList<String[]> listaCliente = RelatorioController.RSC(inicio, fim);

            DefaultTableModel tmCliente = new DefaultTableModel();

            tmCliente.addColumn("ID Cliente");
            tmCliente.addColumn("Nome do Cliente");
            tmCliente.addColumn("CPF");
            tmCliente.addColumn("Valor de todos pedidos");

            tbl_clinetes.setModel(tmCliente);

            tmCliente.setRowCount(0);

            for (String[] p : listaCliente){
                tmCliente.addRow(p);
            }

            tbl_clinetes.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbl_clinetes.getColumnModel().getColumn(1).setPreferredWidth(150);
            tbl_clinetes.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbl_clinetes.getColumnModel().getColumn(3).setPreferredWidth(125);
        }else{
            JOptionPane.showMessageDialog(this, "Data inválida\nverifique os campos das datas");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Gbnt_TipoRelato;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdata_fim;
    private com.toedter.calendar.JDateChooser jdata_inicio;
    private javax.swing.JRadioButton rbtn_Analitico;
    private javax.swing.JRadioButton rbtn_Sintetico;
    private javax.swing.JTable tbl_Items;
    private javax.swing.JTable tbl_clinetes;
    // End of variables declaration//GEN-END:variables
}
